import React, { useContext, useCallback } from "react";
import Head from "next/head";
import Image from "next/image";
import Web3 from "web3";
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";

import { useRouter } from "next/router";

import { Form, Modal } from "@/components";
import { Hero } from "@/sections";
import CreateMeetContext from "@/context/MeetContext";
import { shortenAddress } from "@/utils/shortenAddr";

import { Navbar, Info } from "@/components";
import Background from "@/components/Background";

export default function Home() {
  const {
    address,
    setAddress,
    toggleModal,
    setToggleModal,
    checkNftBalance,
    connectWallet,
  } = useContext(CreateMeetContext);

  const particlesInit = useCallback(async (engine) => {
    console.log(engine);

    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(async (container) => {
    await console.log(container);
  }, []);

  const router = useRouter();

  const checkNftAuth = async () => {
    const response = await checkNftBalance();

    if (response) {
      router.push("/explore");
    } else {
      alert("Please register before proceeding!!");
    }
  };

  return (
    <div>
      {/* <Navbar explore /> */}
      <Head>
        <title>InfoBase</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='relative'>
        {toggleModal && (
          <div className='fixed z-50 top-0 bottom-0 left-0 right-0 w-[100vw] h-[100vh] flex items-center justify-center bg-gray-600 bg-opacity-10 backdrop-filter backdrop-blur-lg'>
            <Modal />
          </div>
        )}

        <div className='h-[100vh] px-[20px] z-30'>
          <div className='absolute right-[20px] top-[20px] space-x-4 z-30'>
            <button
              className='btn btn-outline border-[2px] px-[30px] text-[14px] border-[#950740] text-[#c3073f] hover:bg-[#950740] hover:border-[#950740] hover:text-[#1a1a1d] z-30'
              onClick={() => checkNftAuth()}
            >
              Sign In
            </button>
            {address !== "" ? (
              <button className='text-white btn btn-outline border-[2px] px-[30px] text-[14px] border-[#950740] hover:bg-[#950740] hover:border-[#950740] hover:text-[#1a1a1d] z-30'>
                {shortenAddress(address)}
              </button>
            ) : (
              <button
                className='btn btn-outline border-[2px] px-[30px] text-[14px] border-[#950740] text-[#c3073f] hover:bg-[#950740] hover:border-[#950740] hover:text-[#1a1a1d] z-30'
                onClick={() => connectWallet()}
              >
                connect wallet
              </button>
            )}
          </div>

          <div className='flex'>
            <div className='flex-1 z-40 mt-[120px] flex items-center justify-center w-full'>
              <div className='flex flex-col items-center justify-center w-fit'>
                <p className='text-[100px] mb-[30px] mr-[250px] font-bold text-grad'>
                  InfoBase
                </p>
                <div className='content'>
                  <h2 className='font-bold'>Explore.Collaborate.Earn</h2>
                  <h2 className='font-bold'>Explore.Collaborate.Earn</h2>
                </div>
              </div>
            </div>

            <div className='flex-1 z-40 mt-[120px] flex items-center justify-center '>
              <Form />
            </div>
          </div>
        </div>

        {/* <div className='absolute top-0 bottom-0 right-0 left-0'>
          <Particles
            id='tsparticles'
            url='http://foo.bar/particles.json'
            init={particlesInit}
            loaded={particlesLoaded}
          />
        </div> */}
        <Particles
          id='tsparticles'
          init={particlesInit}
          loaded={particlesLoaded}
          options={{
            background: {
              color: {
                value: "#1a1a1d",
              },
            },
            fpsLimit: 120,
            interactivity: {
              events: {
                onClick: {
                  enable: true,
                  mode: "push",
                },
                onHover: {
                  enable: true,
                  mode: "repulse",
                },
                resize: true,
              },
              modes: {
                push: {
                  quantity: 4,
                },
                repulse: {
                  distance: 200,
                  duration: 0.4,
                },
              },
            },
            particles: {
              color: {
                value: "#4e4e50",
              },
              links: {
                color: "#4e4e50",
                distance: 150,
                enable: true,
                opacity: 0.5,
                width: 1,
              },
              collisions: {
                enable: true,
              },
              move: {
                direction: "none",
                enable: true,
                outModes: {
                  default: "bounce",
                },
                random: false,
                speed: 2,
                straight: false,
              },
              number: {
                density: {
                  enable: true,
                  area: 800,
                },
                value: 80,
              },
              opacity: {
                value: 0.5,
              },
              shape: {
                type: "circle",
              },
              size: {
                value: { min: 1, max: 5 },
              },
            },
            detectRetina: true,
          }}
        />
      </main>
    </div>
  );
}
